### PR TITLE
Update Lattice.md

### PR DESCRIPTION
**Pull request by egull**

### CODE REVIEW

**Review by iskakoff — COMMENTED** [review]
Are you sure that `[(0.0, 0.0, 0.0),(0, 0, 0.5)],` is the correct position for a primitive cell?

**Comment by egull** [comment]
If I understand this script right then what we input is the CONVENTIONAL cell. What it outputs is the PRIMITIVE cell. The coordinates are the ones for the input.

Here are the input values I used:

https://next-gen.materialsproject.org/materials/mp-23703?chemsys=Li-H

Li is at Wyckoff 4a, Hydrogen at 4b.

Emanuel

**Comment by egull** [comment]
Sergei, do you agree or am I understanding this wrong?

**Comment by iskakoff** [comment]
I would check it first. Because in the conventional cell we have 8 atoms, not 2.

**Pull request closed without merging**
